const crossfitExercises = {
    crossfit: [
        { name: 'Burpees', variations: [], minLevel: 'principiante', video: 'https://hips.hearstapps.com/hmg-prod/images/workouts/2016/03/burpee-1457045324.gif' },
        { name: 'Air Squats', variations: [], minLevel: 'principiante', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/493.gif' },
        { name: 'Push-Ups', variations: ['normales', 'diamante'], minLevel: 'principiante', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/47.gif' },
        { name: 'Pull-Ups', variations: ['pronadas', 'supinadas'], minLevel: 'novato', video: 'https://cdn.shopify.com/s/files/1/0568/6280/2107/files/traction-pronation_480x480.gif' },
        { name: 'Kettlebell Swings', variations: [], minLevel: 'principiante', video: 'https://hips.hearstapps.com/hmg-prod/images/workouts/2016/03/kettlebellswing-1457030481.gif?resize=640:*' },
        { name: 'Wall Balls', variations: [], minLevel: 'principiante', video: 'https://images.ctfassets.net/8urtyqugdt2l/7rzoLR81pmtqa5MARFF8vJ/9759b3d72d5ceeef36ec8f9fb9528f66/wall_ball_exercise.gif' },
        { name: 'Box Jumps', variations: [], minLevel: 'principiante', video: 'https://www.verywellfit.com/thmb/ONDejPIpuoMG9tRlRwrGoNmI3C4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/3-4588131-BOX-JUMPS-GIF-aebb1aa40325480aa2a69d5e41e51bce.gif' },
        { name: 'Clean and Jerk', variations: [], minLevel: 'principiante', video: 'https://hips.hearstapps.com/menshealth-uk/main/assets/CleanJerk.gif?resize=980:*' },
        { name: 'Power snatch', variations: [], minLevel: 'principiante', video: 'https://media.tenor.com/bV-Wr6nO-TQAAAAM/lifting-snatch.gif' },
        { name: 'Muscle-Ups', variations: [], minLevel: 'maestro', video: 'https://cdn.shopify.com/s/files/1/0568/6280/2107/files/muscle-up-barre-de-traction_480x480.gif' },
        { name: 'Handstand Push-Ups', variations: [], minLevel: 'maestro', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/875.gif' },
        { name: 'Double-Unders', variations: [], minLevel: 'principiante', video: 'https://www.crossfit.com/wp-content/uploads/2022/10/20053158/Double-Unders.gif' },
        { name: 'Rope Climbs', variations: [], minLevel: 'experto', video: '' },
        { name: 'Barbell Thrusters', variations: [], minLevel: 'principiante', video: 'https://media.post.rvohealth.io/wp-content/uploads/2023/08/MixedLeadingApatosaur-size_restricted.gif' },
        { name: 'Deadlift', variations: ['sumo', 'convencional'], minLevel: 'principiante', video: 'https://www.verywellfit.com/thmb/Tx8RFZxwSVa8PmfQVV8TwRQOrvY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/21-3498608-Deadlift-GIF-b76ce11dc6ef403fa0bf19f252e4b39e.gif' },
        { name: 'Overhead Squats', variations: [], minLevel: 'principiante', video: 'https://www.verywellfit.com/thmb/VsvPDOeokte1GmT6Sg8NoLEdrL0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/25-Overhead-Squat-GIF-95c8bb4f192849fe9204da7c6ee3526d.gif' },
        { name: 'Pistols', variations: [], minLevel: 'novato', video: 'https://htv.com.pk/wp-content/uploads/75-TRX-Pistol-Squat-GIF1-fd69db098e2b4486bf51b0fb52ae1517.gif' },
        { name: 'Farmer’s Carry', variations: [], minLevel: 'principiante', video: 'https://www.verywellfit.com/thmb/JHjO_2UU0SV5J5ln0aKwp1clcVk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/13-Farmers-Carry-GIF-ae7d9ca0c5be485987c72a1e7d944538.gif' },
        { name: 'Lunges', variations: ['con barra', 'con mancuernas'], minLevel: 'principiante', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/1215.gif' },
        { name: 'Planche Holds', variations: [], minLevel: 'experto', video: 'https://themovementathlete.com/wp-content/uploads/Full-Planche_Gif_Small_360x240_11.9-MB.gif' },
        { name: 'Front Lever', variations: [], minLevel: 'maestro', video: '' },
        { name: 'Toes to Bar', variations: [], minLevel: 'novato', video: 'https://64.media.tumblr.com/f2db62fc7ecfd26d5e58f56d023b4487/tumblr_otxd3bEO0N1w2o6e1o1_500.gif' },
        { name: 'Sit-ups', variations: [], minLevel: 'principiante', video: 'https://downloads.ctfassets.net/6ilvqec50fal/7EclbKjErS5Won9rpnOQ4q/5bdec6988da9a730667f337fa5da461f/How-to-do-a-sit-up-GIF.gif' },
        { name: 'Mountain Climbers', variations: [], minLevel: 'principiante', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/484.gif' },
        { name: 'Power-Clean', variations: [], minLevel: 'principiante', video: 'https://www.verywellfit.com/thmb/jpjuKD7wcl2jQIfGIFMZ-oiCaTU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/23-4589787-Power-Clean-GIF-9a230750dd5841d2a26e02fd0af13c6e.gif' },
        { name: 'Squat-Clean', variations: [], minLevel: 'principiante', video: 'https://images.squarespace-cdn.com/content/v1/5160bb45e4b0e13a258812c8/1457723813033-2X546Z1UJAFZ21JAF8QW/image-asset.gif' },
        { name: 'Push Press', variations: [], minLevel: 'principiante', video: 'https://i.pinimg.com/originals/a2/7d/5d/a27d5dc7ffe2ea2fc170905b65337969.gif' },
        { name: 'Push Jerk', variations: [], minLevel: 'principiante', video: 'https://i.makeagif.com/media/8-28-2022/TFuios.gif' },
        { name: 'Split Jerk', variations: [], minLevel: 'principiante', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/945.gif' },
        { name: 'Hang-Clean', variations: [], minLevel: 'principiante', video: 'https://cdn.jefit.com/assets/img/exercises/gifs/900.gif' },
        { name: 'Hang-Snatch', variations: [], minLevel: 'principiante', video: 'https://assets.myworkouts.io/exercises-media/oTE5C3KXKJbAThQDf/hang_snatch_female_v14_gif100px_capoff.gif' },
        { name: 'Goblet squats', variations: [], minLevel: 'principiante', video: 'https://i.pinimg.com/originals/11/a9/6e/11a96e7f29b2e446eed382c3da65a101.gif' },
        { name: 'Kettlebell snatch', variations: [], minLevel: 'principiante', video: 'https://www.verywellfit.com/thmb/DuxfDAHNCmAMyXUY4hdbl3KwTzs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/5-2084649-Kettlebell-Snatch-GIF-ee210704ffc14daabb0507f4828921c7.gif' },
        { name: 'Dumbbell snatch', variations: [], minLevel: 'principiante', video: 'https://lh4.googleusercontent.com/m3WIFncRcXCPHImUIkP5coBGq5XOlXpRjONgQiG4-avBdm70iT-83jOWmjZv0bvrwIyb-NxbzeO6wN1eqm70GJ7whvFp3FYUZso0seZBsLiHaQm30kUPaOElOZUMYwvc6AHC5tp8=s1600' },
        { name: 'Dumbbell thrusters', variations: [], minLevel: 'principiante', video: 'https://hips.hearstapps.com/hmg-prod/images/dumbbell-thrusters-1566400183.gif' },
        { name: 'Dumbbell push press', variations: [], minLevel: 'principiante', video: 'https://hips.hearstapps.com/hmg-prod/images/workouts/2016/03/dumbbellpushuppress-1457031237.gif' },
        
    ],
};

export default crossfitExercises;
